preload = /home/justin/.dotfiles/wallpapers/3840x2400/25cf035b-bac9-4a72-bd3d-d61ce79d9669.jpg

wallpaper {
    monitor = eDP-1
    path = /home/justin/.dotfiles/wallpapers/3840x2400/25cf035b-bac9-4a72-bd3d-d61ce79d9669.jpg
}

splash = false
