preload = /home/justin/.dotfiles/wallpapers/3840x2400/25cf035b-bac9-4a72-bd3d-d61ce79d9669.jpg
preload = /home/justin/.dotfiles/wallpapers/2880x1440/wallhaven-wallhaven-438x6d_2560x1440.png
preload = /home/justin/.dotfiles/wallpapers/2880x1440/wallhaven-xlz5l3.jpg
preload = /home/justin/.dotfiles/wallpapers/3440x1440/wallhaven-vpo228.jpg
preload = /home/justin/.dotfiles/wallpapers/3440x1440/iEwQG.jpg
preload = /home/justin/.dotfiles/wallpapers/3440x1440/dKqJe.jpg
preload = /home/justin/.dotfiles/wallpapers/3440x1440/koMGi.jpg
preload = /home/justin/.dotfiles/wallpapers/3440x1440/OB-Sys0p.png
preload = /home/justin/.dotfiles/wallpapers/3440x1440/MOB-Sys0p.png

wallpaper {
    monitor = eDP-1
    path = /home/justin/.dotfiles/wallpapers/2880x1440/wallhaven-xlz5l3.jpg
}

wallpaper {
   monitor = DP-2
   path = /home/justin/.dotfiles/wallpapers/2560x1440/wallhaven-438x6d_2560x1440.jpg
}

wallpaper {
   monitor = DP-3
   path = /home/justin/.dotfiles/wallpapers/3440x1440/MOB-Sys0p.png
}
   splash = false
