preload = /home/justin/.dotfiles/wallpapers/3840x2400/25cf035b-bac9-4a72-bd3d-d61ce79d9669.jpg
preload = /home/justin/.dotfiles/wallpapers/2880x1440/wallhaven-xlz5l3.jpg
preload = /home/justin/.dotfiles/wallpapers/3440x1440/wallhaven-vpo228.jpg
preload = /home/justin/.dotfiles/wallpapers/3440x1440/iEwQG.jpg
preload = /home/justin/.dotfiles/wallpapers/3440x1440/dKqJe.jpg
preload = /home/justin/.dotfiles/wallpapers/3440x1440/koMGi.jpg
preload = /home/justin/.dotfiles/wallpapers/3440x1440/OB-Sys0p.png
preload = /home/justin/.dotfiles/wallpapers/3440x1440/MOB-Sys0p.png

$LAPTOP  = eDP-1
$ACER    = desc:Acer Technologies Acer X34
$SAMSUNG = desc:Samsung Electric Company C27JG5x HTOK800290

wallpaper {
    monitor = $LAPTOP
    path    = /home/justin/.dotfiles/wallpapers/2880x1440/wallhaven-xlz5l3.jpg
}

wallpaper {
    monitor = $SAMSUNG
    path    = /home/justin/.dotfiles/wallpapers/2560x1440/wallhaven-438x6d_2560x1440.png   # fix the actual filename/path
}

wallpaper {
    monitor = $ACER
    path    = /home/justin/.dotfiles/wallpapers/3440x1440/MOB-Sys0p.png
}

# Optional fallback for any other monitor
# wallpaper {
#     monitor =
#     path    = /path/to/fallback.jpg
# }

splash = false
