default_entry: 1
timeout: 3
remember_last_entry: yes

/Arch Linux
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: root=UUID=2c04bc27-3285-412f-8c93-4a85fc973c44 rootflags=subvol=@ rw resume=UUID=2c04bc27-3285-412f-8c93-4a85fc973c44 resume_offset=533760
    module_path: boot():/amd-ucode.img
    module_path: boot():/initramfs-linux.img

/Arch Linux (Zen)
    protocol: linux
    path: boot():/vmlinuz-linux-zen
    cmdline: root=UUID=2c04bc27-3285-412f-8c93-4a85fc973c44 rootflags=subvol=@ rw resume=UUID=2c04bc27-3285-412f-8c93-4a85fc973c44 resume_offset=533760
    module_path: boot():/amd-ucode.img
    module_path: boot():/initramfs-linux-zen.img
