timeout: 3
default_entry: 2          # 1 = first entry, 2 = second entry
remember_last_entry: yes

/Arch Linux (linux)
    protocol: efi
    path: boot():/EFI/Linux/arch-linux.efi
    cmdline: root=/dev/ArchinstallVg/root zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs

/Arch Linux (linux-zen)
    protocol: efi
    path: boot():/EFI/Linux/arch-linux-zen.efi
    cmdline: root=/dev/ArchinstallVg/root zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs

[root@Sys0p BOOT]# 
